version: '3'
services: 
    app:
        build: 
            context: ./
            dockerfile: ./dockerfiles/python/Dockerfile
        tty: true
        ports: 
            - 8000:8000
        volumes: 
            - ./:/app
        depends_on:
            - db

    db:
        build: ./dockerfiles/mysql
        ports:
            - 3306:3306
        volumes:
            - ./db:/var/lib/mysql
